{
	"version": 1476810175,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/white_button-sheet0.png",
		"images/tall_white_button-sheet0.png",
		"images/tall_white_button2-sheet0.png",
		"images/green_button2-sheet0.png",
		"images/red_button1-sheet0.png",
		"images/fadein-sheet0.png",
		"images/sound-sheet0.png",
		"images/sound-sheet1.png",
		"images/logo_url-sheet0.png",
		"images/tiledbackground.png",
		"images/larger-sheet0.png",
		"images/smaller-sheet0.png",
		"media/correct.ogg",
		"media/game_over.ogg",
		"media/new_highscore.ogg",
		"media/wrong.ogg",
		"media/you_win.ogg",
		"media/christmas synths.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"questions.txt",
		"title.txt"
	]
}